---
synapse:
  exports: 
    id: syn20852283
    name: External REDCap exports
    type: folder
    description: folder containing subfolders containing BPC upload files
  testing: 
    id: syn27538188
    name: External REDCap exports
    type: folder
    description: folder containing subfolders containing test upload files
  reports:
    id: syn25832316
    name: QA Check
    type: folder
    description: folder containing all QA reports by cohort
cohorts:
- BLADDER
- BrCa
- CRC
- CRC2
- NSCLC
- NSCLC2
- PANC
- Prostate
- MELANOMA
- ESOPHAGO
- OVARIAN
- RENAL
reports:
- upload
- masking
contacts:
  DFCI:
  - xindi.guo
  - thomas.yu
  - chelsea.nayan
  - alyssa.acebedo
  - Mi31953
  - apostle
  - karimfarhat
  - Ashnewc
  - ddand
  - daniel_quinn
  - myp74
  MSK:
  - xindi.guo
  - thomas.yu
  - chelsea.nayan
  - alyssa.acebedo
  - Mi31953
  - pillais
  - julia.e.rudolph
  UHN:
  - xindi.guo
  - thomas.yu
  - chelsea.nayan
  - alyssa.acebedo
  - Mi31953
  - celeste.yu
  VICC:
  - thomas.yu
  - xindi.guo
  - chelsea.nayan
  - alyssa.acebedo
  - Mi31953
  - Michele
  - nonnapotter
  UCSF:
  - thomas.yu
  - xindi.guo
  - chelsea.nayan
  - alyssa.acebedo
  - Mi31953
  - mturski18
  - elanaweingord
  SAGE:
  - xindi.guo
  - thomas.yu
  - chelsea.nayan
  PROV:
  - thomas.yu
  - xindi.guo
  - chelsea.nayan
  - alyssa.acebedo
  - Mi31953
  - shwethapindikuri
  WAKE: # Need contacts
  - thomas.yu
  - xindi.guo
  - chelsea.nayan
  - alyssa.acebedo
  - Mi31953
  JHU: # Need contacts
  - thomas.yu
  - xindi.guo
  - chelsea.nayan
  - alyssa.acebedo
  - Mi31953
  VHIO:
  - thomas.yu
  - xindi.guo
  - chelsea.nayan
  - alyssa.acebedo
  - Mi31953
  - apedrola
